// 公司实体
export interface Company {
  id: string;
  name: string;
  type: 'listed' | 'non-listed'; // 上市 | 非上市
  matchedNameInOtherBooks?: string; // 在对方账套里的名称 (用于对账)
}

// 系统配置
export interface SystemConfig {
  mappingTemplates: MappingTemplate[];
  incomeSubjectCodes: string[]; // 收入类科目 (e.g., 6001)
  costSubjectCodes: string[];   // 成本费用类科目 (e.g., 6401, 6602)
  accountSegmentIndex: number;
  subAccountSegmentIndex: number;
  departmentMap: Record<string, string>;
  
  // New: 关联方配置
  entities: Company[];
}

// 字段映射模板
export interface MappingTemplate {
  id: string;
  name: string; 
  type: 'ledger' | 'balance'; 
  columnMap: Record<string, string>; 
}

// 导入历史记录
export interface ImportHistoryItem {
  id: string;
  entityId: string; // 所属主体
  fileName: string;
  importDate: string; 
  recordCount: number;
  type: 'ledger' | 'balance';
  status: 'success' | 'failed';
}

// 1. 财务流水 (账户明细表)
export interface LedgerRow {
  id?: string | number; // Updated to support string IDs generated by utils
  entityId?: string; // Optional during parsing

  voucherNo: string;      
  date: string;           
  period: string;         // YYYY-MM
  summary: string;        
  
  subjectCode: string;     
  subjectName: string;     
  department?: string;     

  debitAmount: number;    
  creditAmount: number;   

  counterparty?: string;   
  rawReference?: string;   
}

// 2. 科目余额表行
export interface BalanceRow {
  id?: string | number; // Updated to support string IDs generated by utils
  entityId?: string; // Optional during parsing

  period: string;        
  subjectCode: string;   
  subjectName: string;   
  
  accountElement?: string; 
  costCenter?: string;     
  costCenterCode?: string; 
  counterparty?: string;   

  openingBalance: number; 
  debitPeriod: number;    
  creditPeriod: number;   
  closingBalance: number; 
}

// Aliases for FinancePage compatibility
export type TrialBalanceRow = LedgerRow;
export type SubjectBalanceRow = BalanceRow;

// --- New Interfaces for Dashboard / Contract / AssetMap ---

export enum PartnerType {
  RELATED = 'RELATED',
  EXTERNAL = 'EXTERNAL'
}

export interface LeaseContract {
  id: string;
  contractNo: string;
  name: string;
  tenantName: string;
  partnerType: PartnerType;
  type: string;
  rentAmount: number;
  paymentCycle: string;
  startDate: string;
  endDate: string;
  status: string;
  aiAnalysis?: string;
  unitIds?: string[];
  propertyFee?: number;
}

export enum AssetStatus {
  LEASED = '已出租',
  VACANT = '空置',
  MAINTENANCE = '维修',
  SELF_USE = '自用'
}

export interface AssetUnit {
  id: string;
  code: string;
  status: AssetStatus | string;
  area: number;
  building: string;
  floor: number;
}

export interface ReceivablePlan {
  id: string;
  period: string;
  planAmount: number;
  matchedAmount: number;
  type: string;
  status: string;
  matchDetail?: { matchType: string };
}

export interface UtilityRecord {
  id: string;
  period: string;
  amount: number;
  type: string;
}

// For Gemini Service
export interface AnalysisResult {
  summary: string;
  risks: string[];
  recommendations: string[];
  kpiIndicators: Array<{
    label: string;
    value: string;
    status: string;
  }>;
}